name: React Tofa

on:
  # 커밋을 push할 때 마다 실행되도록 합니다.
  push:
    branches: [master]

jobs:
  # deploy 라는 job 입니다.
  # 안에는 배포에 필요한 과정들을 기술하면 됩니다!
  deploy:
    runs-on: ubuntu-latest # 우분투에서 실행
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      # 레포지토리의 코드를 사용하기 위해 씁니다. 이게 없으면 빈 폴더에요!
      - name: Copy branch
        uses: actions/checkout@v3

      # node 버전 설정 및 인스톨
      - name: Set Node js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies    # 의존 파일 설치
        run: npm install

      - name: Generate build          # React Build
        run: npm run build

      # master branch의 build 폴더에 들어있는 파일들을 gh-pages 브랜치에 올려줍니다.
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build